# Generated by Django 4.2.30 on 2026-05-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='sr_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
