# Generated by Django 4.2.30 on 2026-05-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_entry_note_closedat_status_item_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strict_mode', models.BooleanField(default=False)),
                ('grace_period_days', models.IntegerField(default=5)),
                ('five_day_logic', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='default_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
