# Generated by Django 4.2.30 on 2026-05-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_businesssetting_party_default_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelleryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
