# Generated by Django 4.2.30 on 2026-05-17 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_jewelleryitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='sync_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='sync_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='sync_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
