# Generated by Django 4.2.30 on 2026-05-17 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_entry_sync_id_jewelleryitem_sync_id_party_sync_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('EDIT', 'Edited'), ('DELETE', 'Deleted'), ('WITHDRAW', 'Withdrawn'), ('OVERDUE', 'Marked Overdue'), ('STATUS', 'Status Changed')], max_length=20)),
                ('description', models.TextField()),
                ('actor', models.CharField(default='Owner', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.entry')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
