# Generated by Django 4.2.30 on 2026-05-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_entry_due_date_version_party_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
