# Generated by Django 4.2.30 on 2026-05-19 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_alter_auditlog_action_userprofile_partialpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('EDIT', 'Edited'), ('DELETE', 'Deleted'), ('WITHDRAW', 'Withdrawn'), ('PAYMENT', 'Partial Payment'), ('PROFILE', 'Profile Update')], max_length=20)),
                ('entity_type', models.CharField(choices=[('PARTY', 'Party'), ('ENTRY', 'Entry'), ('ITEM', 'Item'), ('PAYMENT', 'Payment'), ('PROFILE', 'Profile')], max_length=20)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('entity_sync_id', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('description', models.TextField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
