# Generated by Django 4.2.30 on 2026-06-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelleryitem',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='release_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='release_status',
            field=models.CharField(choices=[('held', 'Held'), ('released', 'Released'), ('transferred', 'Transferred')], default='held', max_length=20),
        ),
        migrations.AddField(
            model_name='party',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
